src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java

Originally cherry-picked from PR https://github.com/DataDog/jenkins-datadog-plugin/pull/23 submitted by @dmabamboo

Use isJobTracked() when sorting out blacklist

---

CHANGELOG.md
README.md
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java

Originally cherry-picked from PR https://github.com/DataDog/jenkins-datadog-plugin/pull/23 submitted by @dmabamboo

Utilize java.util.Logger and use best practices for String manipulation

---

.gitignore
CHANGELOG.md
README.md
TESTING.md
pom.xml
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogBuildListener/global.jelly

Rebased from PR https://github.com/DataDog/jenkins-datadog-plugin/pull/25 submitted by @seattletechie

Adding proxy support

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogSCMListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java

Hi @JohnLZeller 
I made this pull request because there is a potential for a NPE when DataDog Job Properties are not selected. 
I think this one is safe to merge and include.

Fixed a possible NPE that can occur when properties are not turned on

---

src/main/java/org/datadog/jenkins/plugins/datadog/BuildFinishedEventImpl.java
src/main/java/org/datadog/jenkins/plugins/datadog/BuildStartedEventImpl.java
src/main/java/org/datadog/jenkins/plugins/datadog/CheckoutCompletedEventImpl.java

Was implemented in f00b261 but got reverted (not intentionally afaik) when #38 was merged

Use Jenkins source type for all events

---

pom.xml
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogHttpRequests.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogJobProperty.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogSCMListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java

The findbugs plugin output spotted a bunch of bugs. This fixes those.

Bugfixes from findbugs

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java

Add in setHostName(String newHostName) and setApiKey(String newApiKey)
to allow automated configuration using groovy.

Add in setters for Hostname / ApiKey

---

.gitignore
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogSCMListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java

Rebasing work done in https://github.com/DataDog/jenkins-datadog-plugin/pull/68

Capture subfolder job names in job tag

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogSCMListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogBuildListener/global.jelly

Reverts DataDog/jenkins-datadog-plugin#78
Let's revert until we fix the tests/code(?)

Revert "Add whitelist configuration option"

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogSCMListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
src/test/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListenerTest.java

Use fullName instead of fullDisplayName for compatibility with multibranch workflow

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java

We've encountered issue #102 and this is a fix we applied and tested.
Fixes #102

Fix: empty whitelist should permit all jobs

---

CHANGELOG.md
pom.xml

Prepare for 0.6.2 release

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogBuildListener/help-targetMetricURL.html

Update Datadog API endpoint

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java

When computing the `jenkins.job.waiting` metric we call `item.getInQueueSince()`. This may raise a `NullPointerException`, as seen with the ec2-spot-jenkins-plugin. This PR catches the NPE and skips sending the gauge metric.

Catch NPE when item.getInQueueSince() is unavailable

---

DEVELOPMENT.md
README.md

Creates a DEVELOPMENT.md file that showcases a quick way to get started with developing on this project.

Add development readme

---

README.md
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java

Takes the work of #132 and adds on top of it. 
Since 132 was a fork I couldn't add commits directly to it, I've made this new PR but was able to keep original commit authorship here.

Send Delivery KPIs

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java

This PRs sends additional metrics to Datadog to measure the performance of teams. It's based on the  [blog post](https://stelligent.com/2017/11/16/codepipeline-dashboard/) from Stelligent.
Each `Job`  provides
- Lead Time
- Cycle Time
- Feedback Time
- MTTR
- MTBF
From [https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details](https://github.com/stelligent/pipeline-dashboard/blob/master/README.md#metric-details)

Send delivery KPIs (fixes #130)

---

src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java

Add build result statuses to match BuildFinishedEventImpl.java
Follow code style there instead of having strings, import class
Handle unknown status just in case

Buildlistener add statuses 

---

.github/CODEOWNERS
CONTRIBUTING.md
README.md

- Fixes https://github.com/DataDog/jenkins-datadog-plugin/issues/31
- Adds github codeowners

Add Codeowner and contributing doc

---

pom.xml
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogJobProperty.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogQueueListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogSCMListener.java
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogUtilities.java
src/main/java/org/datadog/jenkins/plugins/datadog/clients/DatadogHttpClient.java
src/main/java/org/datadog/jenkins/plugins/datadog/events/AbstractDatadogEvent.java
src/main/java/org/datadog/jenkins/plugins/datadog/events/BuildFinishedEventImpl.java
src/main/java/org/datadog/jenkins/plugins/datadog/events/BuildStartedEventImpl.java
src/main/java/org/datadog/jenkins/plugins/datadog/events/CheckoutCompletedEventImpl.java
src/main/java/org/datadog/jenkins/plugins/datadog/model/BuildData.java
src/main/java/org/datadog/jenkins/plugins/datadog/publishers/DatadogCountersPublisher.java
src/main/resources/org/datadog/jenkins/plugins/datadog/DatadogBuildListener/global.jelly
src/test/java/org/datadog/jenkins/plugins/datadog/DatadogBuildListenerTest.java
src/test/java/org/datadog/jenkins/plugins/datadog/DatadogUtilitiesTest.java
src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientStub.java
src/test/java/org/datadog/jenkins/plugins/datadog/clients/DatadogClientTest.java
src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildFinishedEventTest.java
src/test/java/org/datadog/jenkins/plugins/datadog/events/BuildStartedEventTest.java
src/test/java/org/datadog/jenkins/plugins/datadog/events/CheckoutCompletedEventTest.java

- Fixes https://github.com/DataDog/jenkins-datadog-plugin/issues/157
- Fixes https://github.com/DataDog/jenkins-datadog-plugin/issues/113
- Set node tag by default
- Added Api Key and Target URL validation during client instanciatin
- Remove dogstatsd dependency in pom file

Allow multiple values for tags & Support prefix for White/Blacklist & More

---

.azure-pipelines/all.yml
pom.xml

Fixes https://github.com/DataDog/jenkins-datadog-plugin/issues/3

enable checks

---

README.md
src/main/java/org/datadog/jenkins/plugins/datadog/DatadogGlobalConfiguration.java

- Fixes https://github.com/DataDog/jenkins-datadog-plugin/issues/116

configure plugin using env vars

---

README.md

The old wiki link page is deprecated and it asks you to go to the plugin page anyway. Let's link people to the right place.
* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix one issue at the time.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see [CONTRIBUTING](/CONTRIBUTING.md). 
Updates the Jenkins plugin page link in the README.

Update Plugin Page Link
